:bug: fix auto merge action

diff --git a/.github/workflows/weekly-build.yml b/.github/workflows/weekly-build.yml
--- a/.github/workflows/weekly-build.yml
+++ b/.github/workflows/weekly-build.yml
@@ -27,13 +27,15 @@ jobs:
           else
             echo "PR already exists: $PR_URL"
           fi
-          echo "pr_url=$PR_URL" >> $GITHUB_ENV
+          echo "pr_target_url=$PR_URL" >> $GITHUB_ENV
   auto_merge:
     needs: create_pull_request
     runs-on: ubuntu-latest
     steps:
+      - uses: actions/checkout@v4
       - name: Auto merge PR
-        if: env.pr_url != ''
+        env:
+          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
         run: |
-          gh pr merge "${{ env.pr_url }}" --rebase --auto \
-            || echo "Failed to auto-merge the PR"
+          echo "Auto-merging PR: $pr_target_url"
+          gh pr merge "$pr_target_url" --rebase --auto || echo "Failed to auto-merge the PR"
